hostname_style = "#9ece6a"
directory_style = "#7aa2f7"
directory_read_only_style = "#f7768e"
git_branch_style = "#a9b1d6"
git_state_style = "#a9b1d6"
git_status_style = "#a9b1d6"
character_success = "#9ece6a"
character_error = "#9ece6a"
character_vimcmd = "#7aa2f7"
character_vimcmd_visual = "#bb9af7"
character_vimcmd_replace = "#f7768e"
character_vimcmd_replace_one = "#f7768e"
