# Nvidia settings
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

# Remap the Caps Lock key with the CTRL key when pressed with another key
setxkbmap -option 'caps:ctrl_modifier'

# Remap the Caps Lock key with the ESC key when presses alone
xcape -e 'Caps_Lock=Escape'

xrdb -merge ~/.config/X11/.Xresources
exec i3
