directory_style = "#2e7de9"
directory_read_only_style = "#f52a65"
git_branch_style = "#6172b0"
git_state_style = "#6172b0"
git_status_style = "#6172b0"
character_success = "#587539"
character_error = "#587539"
character_vimcmd = "#2e7de9"
character_vimcmd_visual = "#9854f1"
character_vimcmd_replace = "#f52a65"
character_vimcmd_replace_one = "#f52a65"
