[colors.primary]
background = '#e1e2e7'
foreground = '#3760bf'

[colors.cursor]
cursor = '#3760bf'
text = '#e1e2e7'

[colors.normal]
black = '#b4b5b9'
blue = '#2e7de9'
cyan = '#007197'
green = '#587539'
magenta = '#9854f1'
red = '#f52a65'
white = '#6172b0'
yellow = '#8c6c3e'

[colors.bright]
black = '#a1a6c5'
blue = '#358aff'
cyan = '#007ea8'
green = '#5c8524'
magenta = '#a463ff'
red = '#ff4774'
white = '#3760bf'
yellow = '#a27629'
