[general]
import = ["/home/claudio/dotfiles/themes/tokyonight-night/alacritty.toml"]

[window]
title = "alacritty"
dynamic_title = false
decorations_theme_variant = "Dark"

[font]
size = 14.0

[font.normal]
family = "DankMono Nerd Font"
style = "Regular"

[font.bold]
family = "DankMono Nerd Font"
style = "Bold"

[font.italic]
family = "DankMono Nerd Font"
style = "Italic"
