[packages]
apps = [
	"alacritty",
	"beekeeper-studio-bin",
	"firefox",
	"gimp"
]
bluetooth = [
	"bluez",
	"bluez-utils"
]
command-line = [
	"git"
]
file-system-tools = [
	"dosfstools",
	"exfatprogs",
	"ntfs-3g"
]
fonts = [
	"ttf-dejavu",
	"ttf-sourcecodepro-nerd"
]

