[packages]
apps = [
	"alacritty",
	"beekeeper-studio-bin",
	"firefox",
	"flameshot",
	"gimp",
	"klavaro",
	"obsidian"
]
bluetooth = [
	"bluez",
	"bluez-utils"
]
command-line = [
	"fd",
	"fish",
	"git",
	"gum",
	"htop",
	"man",
	"man-pages",
	"neofetch",
	"neovim",
	"openssh",
	"poppler",
	"ripgrep",
	"udiskie",
	"unzip",
	"xclip",
	"zip"
]
file-system-tools = [
	"dosfstools",
	"exfatprogs",
	"ntfs-3g"
]
fonts = [
	"ttf-dejavu",
	"ttf-sourcecodepro-nerd"
]
i3 = [
	"xorg",
	"xorg-xinit",
	"xsettingsd",
	"i3-wm",
	"i3status",
	"i3lock",
	"dmenu",
	"arandr",
]
podman = [
	"podman",
	"podman-compose"
]
themes = [
	"arc-gtk-theme",
	"arc-icon-theme",
	"rose-pine-cursor",
	"nwg-look"
]
virtualization = [
	"qemu-full",
	"libvirt",
	"virt-manager",
	"iptables-nft",
	"dnsmasq",
	"dmidecode",
	"edk2-ovmf"
]
zathura = [
	"zathura",
	"zathura-cb",
	"zathura-djvu",
	"zathura-pdf-mupdf",
	"zathura-ps"
]
