[packages]
apps = [
	"alacritty",
	"beekeeper-studio-bin",
	"firefox",
	"gimp",
	"klavaro"
]
bluetooth = [
	"bluez",
	"bluez-utils"
]
command-line = [
	"git"
]
file-system-tools = [
	"dosfstools",
	"exfatprogs",
	"ntfs-3g"
]
fonts = [
	"ttf-dejavu",
	"ttf-sourcecodepro-nerd"
]
i3 = [
	"xorg",
	"xorg-xinit",
	"xsettingsd",
	"i3-wm",
	"i3status",
	"i3lock",
	"dmenu",
	"arandr",
]
virtualization = [
	"qemu-full",
	"libvirt",
	"virt-manager",
	"iptables-nft",
	"dnsmasq",
	"dmidecode",
	"edk2-ovmf"
]
