hostname_style = "#c3e88d"
directory_style = "#82aaff"
directory_read_only_style = "#ff757f"
git_branch_style = "#828bb8"
git_state_style = "#828bb8"
git_status_style = "#828bb8"
character_success = "#c3e88d"
character_error = "#c3e88d"
character_vimcmd = "#82aaff"
character_vimcmd_visual = "#c099ff"
character_vimcmd_replace = "#ff757f"
character_vimcmd_replace_one = "#ff757f"
